install.packages('tidyverse')
install.packages('xaringan')
install.packages('palmerpenguins')
install.packages('gapminder')
install.packages('ggthemes')
install.packages('tibbletime')
install.packages('remotes')
remotes::install_github('bbc/bbplot')